// WYGENEROWANE z nb-cms/scripts/page-texts/spec.mjs — nie edytuj ręcznie.
// Teksty startowe każdego formularza „Strona: …” w CMS. Strona pokazuje je tylko,
// gdy CMS nie ma jeszcze danego pola (np. przed wdrożeniem nowej wersji CMS).
export const pageTextDefaults = {
  "home": {
    "heroKicker": "Ustrzyki Dolne · Bieszczady",
    "heroTitle": "NOWOCZESNE BIESZCZADY",
    "heroSubtitle": "Tworzymy wydarzenia, konkursy i inicjatywy, które budują tożsamość regionu.",
    "heroCta": "Dowiedz się więcej",
    "heroCtaHref": "/o-nas/misja",
    "aboutKicker": "Stowarzyszenie",
    "aboutTitle": "Krótko o nas",
    "aboutParagraph1": "",
    "aboutParagraph2": "",
    "aboutTagline": "„SKUTECZNI DLA WAS”",
    "newsKicker": "Blog",
    "newsTitle": "Najnowsze aktualności",
    "newsAllLink": "Zobacz wszystkie aktualności",
    "themeBackground": "",
    "themeHero": "",
    "themeTitle": "",
    "themeLead": "",
    "themeBody": "",
    "themeAccent": ""
  },
  "site-settings": {
    "email": "biuro@nowoczesnebieszczady.pl",
    "phone": "507 068 728",
    "address": "Ustrzyki Dolne, woj. podkarpackie",
    "facebookUrl": "https://www.facebook.com/nowoczesne.bieszczady/?locale=pl_PL",
    "facebookLabel": "Facebook",
    "footerTitle": "NOWOCZESNE BIESZCZADY",
    "footerTagline": "Stowarzyszenie działające na rzecz rozwoju regionu",
    "footerDownloads": "Do pobrania",
    "footerCopyright": "© {rok} Nowoczesne Bieszczady. Wszystkie prawa zastrzeżone.",
    "readMore": "Czytaj więcej →",
    "readFull": "Czytaj całość",
    "readLess": "Zwiń",
    "relatedKicker": "Aktualności",
    "relatedTitle": "Powiązane aktualności",
    "relatedAll": "Zobacz wszystkie aktualności →",
    "siteName": "Nowoczesne Bieszczady",
    "galleryShowAll": "Zobacz wszystkie",
    "gallerySwipe": "Przesuń, aby zobaczyć więcej →",
    "galleryExpand": "Pokaż wszystkie zdjęcia ({liczba})",
    "galleryCollapse": "Zwiń galerię",
    "colorTitle": "#151d1c",
    "colorLead": "#566c71",
    "colorBody": "#6c7173",
    "colorExtra": "#615b3a",
    "colorAccent": "#a8551f",
    "colorBrand": "#135e24",
    "colorInk": "#1a2420",
    "colorBackground": "#eff2ef",
    "colorSection": "#f3f1ea",
    "colorEasy": "#0072bd",
    "colorMedium": "#9c27b0",
    "colorHard": "#cc0000",
    "difficultyEasy": "Łatwa",
    "difficultyMedium": "Średnia",
    "difficultyHard": "Trudna",
    "bikeMtb": "MTB",
    "bikeGravel": "Gravel",
    "bikeEbike": "E-bike",
    "bikeRoad": "Szosa",
    "cardElevation": "{liczba} m przewyższeń"
  },
  "strona-aktualnosci": {
    "heroKicker": "Blog",
    "heroTitle": "Aktualności",
    "heroDescription": "",
    "statPostsOne": "{liczba} opublikowany wpis",
    "statPostsFew": "{liczba} opublikowane wpisy",
    "statPostsMany": "{liczba} opublikowanych wpisów",
    "statExtra": "Aktualizowane na bieżąco",
    "filterAll": "Wszystkie",
    "pageTitle": "Aktualności",
    "galleryTitle": "Galeria",
    "photosOne": "{liczba} zdjęcie",
    "photosFew": "{liczba} zdjęcia",
    "photosMany": "{liczba} zdjęć",
    "backLink": "← Wróć do aktualności",
    "notFound": "Nie znaleziono wpisu",
    "themeBackground": "",
    "themeHero": "",
    "themeTitle": "",
    "themeLead": "",
    "themeBody": "",
    "themeAccent": ""
  },
  "strona-szlaki": {
    "heroKicker": "Turystyka rowerowa",
    "heroTitle": "Bieszczady na dwóch kołach – 24 trasy sprawdzone przez nas w terenie",
    "heroDescription": "<p>Rozwój turystyki rowerowej w Bieszczadach to jeden z kierunków, na których szczególnie nam zależy. Dlatego na potrzeby aplikacji rowerowej Województwa Podkarpackiego podjęliśmy się audytu tras rowerowych, które osobiście przejechaliśmy i sprawdziliśmy w terenie.</p><p>Łącznie przygotowaliśmy 24 trasy. Za każdą z nich stoją kilometry przejechane na rowerach, dokumentacja fotograficzna, analiza przebiegu oraz dokładne sprawdzenie tego, czego rowerzysta może spodziewać się po drodze.</p><p>Efekty tej pracy udostępniamy również na naszej stronie internetowej, aby mogły służyć zarówno turystom odwiedzającym Bieszczady, jak i mieszkańcom, którzy chcą odkrywać region na dwóch kołach.</p><h2>Wszystko, czego potrzebujesz przed wyjazdem</h2><p>Dla każdej z tras przygotowaliśmy komplet praktycznych informacji. Można pobrać ślad GPX, zobaczyć dokładny przebieg na mapie, sprawdzić długość trasy i profil wysokościowy, obejrzeć zdjęcia oraz zapoznać się z informacjami o miejscach, które mogą wymagać większej uwagi.</p><p>Zaznaczyliśmy również atrakcje znajdujące się na trasie lub w jej bezpośrednim sąsiedztwie – kościoły i cerkwie, punkty oraz platformy widokowe, miejsca związane z historią regionu czy takie atrakcje jak wieża widokowa na Holicy.</p><p>Chcemy, aby przed wyruszeniem w drogę można było nie tylko zobaczyć, którędy prowadzi trasa, ale naprawdę dobrze się do niej przygotować.</p><h2>Wybierz trasę odpowiednią dla siebie</h2><p>Nie każdy szuka tego samego wyzwania, dlatego wszystkie trasy podzieliliśmy według stopnia trudności:</p><ul><li><p>🔵 łatwe – kolor niebieski</p></li><li><p>🟣 średnie – kolor fioletowy</p></li><li><p>🔴 trudne – kolor czerwony</p></li></ul><p>Dzięki temu już na etapie planowania można dobrać trasę do własnej kondycji, doświadczenia, możliwości oraz czasu, którym dysponujemy.</p><p>Przygotowaliśmy również zbiorczą mapę wszystkich 24 tras. Wystarczy wybrać interesującą trasę na mapie, aby przejść do jej szczegółowego opisu i wszystkich przygotowanych przez nas materiałów.</p><h2>Tysiące kilometrów przejechanych po to, żeby ułatwić Wam drogę</h2><p>Przygotowanie całego materiału oznaczało dla nas tysiące kilometrów spędzonych na rowerach i w terenie. Chcieliśmy jednak stworzyć coś, co będzie miało przede wszystkim praktyczną wartość.</p><p>Nie pokazujemy tras wyłącznie jako linii narysowanych na mapie. Przejechaliśmy je, sprawdziliśmy, sfotografowaliśmy i opisaliśmy, zwracając uwagę zarówno na ich największe atuty, jak i miejsca, w których rowerzysta może napotkać trudności.</p><p>Na stronie wskazujemy również sprawdzone przez nas wypożyczalnie rowerów elektrycznych, z których mogą skorzystać osoby niemające własnego sprzętu lub chcące spróbować jazdy na e-bike’u.</p><ul><li><p><a href=\"https://share.google/l0KAYl9A5dbUmx60V\">BiesCzadowe e-Bike – Wypożyczalnia Rowerów Elektrycznych</a></p></li></ul><ul><li><p><a href=\"https://share.google/eIqtoqAl2sPDASxUw\">Bieszczadzka Wypożyczalnia Rowerów Elektrycznych</a></p></li></ul><ul><li><p><a href=\"https://share.google/kD8dCFqGzQjuw5FEW\">Elektrobiesy Wypożyczalnia rowerów elektrycznych</a></p></li></ul><p>Bieszczady mają ogromny potencjał dla turystyki rowerowej. Chcemy pomóc go odkrywać – bezpieczniej, wygodniej i z dobrym przygotowaniem.</p><p>Wybierzcie trasę, pobierzcie GPX, wsiadajcie na rower i ruszajcie z nami w Bieszczady! 🚴‍♂️⛰️</p>",
    "statTrailsOne": "{liczba} zaudytowana trasa",
    "statTrailsFew": "{liczba} zaudytowane trasy",
    "statTrailsMany": "{liczba} zaudytowanych tras",
    "statLength": "{min}–{max} km długości",
    "statLevels": "3 poziomy trudności",
    "pageTitle": "Nasze szlaki rowerowe",
    "mapKicker": "Wszystkie trasy",
    "mapTitle": "Mapa szlaków",
    "mapLead": "Wszystkie zaudytowane trasy na jednej mapie. Kliknij ślad, aby przejść do jego opisu.",
    "mapLoading": "Wczytywanie tras… {liczba}/{wszystkie}",
    "mapHint": "Kliknij mapę, aby przybliżać i przesuwać",
    "mapError": "Nie udało się wczytać śladu: {trasy}.",
    "mapPopupLink": "Zobacz trasę",
    "filterDifficulty": "Trudność",
    "filterBike": "Typ roweru",
    "filterAll": "Wszystkie",
    "filterLength": "Maks. długość",
    "filterReset": "Wyczyść",
    "resultsOne": "Znaleziono {liczba} trasę",
    "resultsFew": "Znaleziono {liczba} trasy",
    "resultsMany": "Znaleziono {liczba} tras",
    "emptyText": "Brak tras spełniających wybrane kryteria.",
    "emptyReset": "Wyczyść filtry i pokaż wszystkie",
    "cardCta": "Zobacz trasę i pobierz GPX",
    "noteKicker": "Projekt „Podkarpacka Rowerowa Przygoda”",
    "noteText": "Trasy w naszej bazie są sukcesywnie audytowane we współpracy z Województwem Podkarpackim. Każdy audyt obejmuje realny przejazd trasy, dokumentację fotograficzną nawierzchni i widoków, pomiar przewyższeń oraz opis miejsc odpoczynku i punktów gastronomicznych.",
    "themeBackground": "",
    "themeHero": "",
    "themeTitle": "",
    "themeLead": "",
    "themeBody": "",
    "themeAccent": ""
  },
  "strona-trasa": {
    "gpxTitle": "Pobierz nawigację GPX",
    "gpxText": "Plik do wgrania na nawigację rowerową lub zegarek GPS.",
    "gpxButton": "Pobierz plik GPX",
    "gpxSoon": "GPX wkrótce dostępny",
    "infoTitle": "Podstawowe informacje",
    "rowName": "Nazwa trasy",
    "rowStart": "Punkt startu/mety",
    "rowCharacter": "Charakter trasy",
    "rowLength": "Długość z GPX",
    "rowElevation": "Przewyższenia z GPX",
    "rowRange": "Zakres wysokości",
    "rowRangeUnit": "m n.p.m.",
    "rowTime": "Szacowany czas przejazdu",
    "rowDifficulty": "Poziom trudności",
    "rowBike": "Rekomendowany rower",
    "rowSurface": "Nawierzchnia",
    "elevationTitle": "Profil wysokościowy",
    "elevationNote": "Wykres poglądowy — pełne dane wysokościowe dostępne w pliku GPX.",
    "mapTitle": "Mapa przebiegu trasy",
    "descriptionTitle": "Opis trasy",
    "overviewLabel": "Przebieg trasy:",
    "waypointsTitle": "Najważniejsze punkty na trasie",
    "waypointsKm": "Km",
    "waypointsPoint": "Punkt / miejscowość",
    "waypointsMeaning": "Znaczenie",
    "highlightsTitle": "Co warto zobaczyć",
    "stopsTitle": "Miejsca odpoczynku i gastronomia",
    "natureTitle": "Walory przyrodnicze",
    "cultureTitle": "Walory historyczne i kulturowe",
    "surfaceTitle": "Nawierzchnia",
    "surfaceAsphalt": "Asfalt",
    "surfaceGravel": "Szuter",
    "surfaceTerrain": "Teren",
    "touristTitle": "Informacje turystyczne i audytowe",
    "recommendationTitle": "Rekomendacja końcowa",
    "safetyTitle": "Bezpieczeństwo",
    "backLink": "← Wróć do wszystkich tras",
    "notFound": "Nie znaleziono trasy",
    "themeBackground": "",
    "themeHero": "",
    "themeTitle": "",
    "themeLead": "",
    "themeBody": "",
    "themeAccent": ""
  },
  "strona-korona": {
    "heroKicker": "Turystyka górska",
    "heroTitle": "Zdobądź Koronę Ustrzyckich Gór!",
    "heroDescription": "<p>Jeżeli lubicie aktywnie spędzać czas i chcecie poznać Ustrzyki Dolne z zupełnie innej perspektywy, mamy dla Was wyjątkową propozycję – Koronę Ustrzyckich Gór.</p><p>To pięć szczytów otaczających Ustrzyki Dolne, które można zdobyć podczas jednej dłuższej wyprawy albo podzielić trasę na kilka krótszych etapów.</p><p>Nasza propozycja rozpoczyna się w Parku Pod Dębami. Stąd ruszamy w kierunku Orlika, następnie przez Gromadzyń i Żuków na Małego Króla, a później na Lawortę, skąd wracamy do Ustrzyk Dolnych i Parku Pod Dębami.</p><p>🥾 Pieszo – przejście całej Korony to już konkretne górskie wyzwanie. W zależności od kondycji i tempa warto zarezerwować na nie około 6–9 godzin.</p><p>🚴‍♂️ Rowerem – trasę można również pokonać na dwóch kółkach. W tym przypadku wyprawa zajmuje zazwyczaj około 3–5 godzin.</p><p>Na naszej stronie, w zakładce Trasy rowerowe – Korona Ustrzyckich Gór, przygotowaliśmy dokładny przebieg trasy. Możecie pobrać ślad GPX, sprawdzić profil i przewyższenia oraz obejrzeć zdjęcia z poszczególnych odcinków. Dzięki temu łatwo zaplanujecie swoją wyprawę i będziecie mogli poruszać się przygotowanym przez nas śladem.</p><p>Nie musicie też zdobywać całej Korony jednego dnia. Trasę podzieliliśmy na mniejsze odcinki, dlatego jeśli macie mniej czasu, możecie poznawać kolejne szczyty podczas kilku osobnych wycieczek.</p><p>📸 A na szczytach czeka dodatkowa motywacja!</p><p>Na każdym z pięciu szczytów znajduje się charakterystyczna figura. Zróbcie przy niej zdjęcie potwierdzające zdobycie szczytu, a po skompletowaniu całej Korony możecie zgłosić się do Centrum Informacji i Promocji w Ustrzykach Dolnych, gdzie czeka nagroda za ukończenie wyzwania.</p><p>Przede wszystkim jednak warto zrobić to dla samej przyjemności wędrowania. Korona Ustrzyckich Gór prowadzi przez miejsca oferujące przepiękne krajobrazy, panoramy Ustrzyk Dolnych i widoki, dla których naprawdę warto zatrzymać się na chwilę.</p><p>Przyjeżdżajcie do Ustrzyk Dolnych, ruszajcie na szlak i zdobywajcie Koronę Ustrzyckich Gór – całą za jednym razem albo szczyt po szczycie.</p><p>Bo Ustrzyki najlepiej poznaje się właśnie z góry. ⛰️</p>",
    "statPeaksOne": "{liczba} szczyt w pętli",
    "statPeaksFew": "{liczba} szczyty w pętli",
    "statPeaksMany": "{liczba} szczytów w pętli",
    "pageTitle": "Korona Ustrzyckich Gór",
    "barPeaksLabel": "Szczytów w pętli",
    "stats": "Długość trasy: 30,9 km\nCzas przejścia: 10–11 godz.\nSuma przewyższeń: 1187 m",
    "peaksKicker": "Pięć szczytów, jedna pętla",
    "peaksTitle": "Szczyty do zdobycia",
    "peaksLead": "Trasa prowadzi kolejno przez pięć wzniesień — zdobycie wszystkich w ramach jednej pętli można potwierdzić pieczątką w Punkcie Informacji Turystycznej w Ustrzykach Dolnych.",
    "peakElevation": "{liczba} m n.p.m.",
    "peakTower": "Wieża widokowa",
    "eventsKicker": "Wydarzenia sportowe",
    "eventsTitle": "Rajdy i mecze terenowe",
    "themeBackground": "",
    "themeHero": "",
    "themeTitle": "",
    "themeLead": "",
    "themeBody": "",
    "themeAccent": ""
  },
  "strona-kultura": {
    "heroKicker": "Kultura",
    "heroTitle": "Kultura i wydarzenia – pokazujemy Bieszczady z innej strony",
    "heroDescription": "<p>Bieszczady to nie tylko góry, szlaki i piękna przyroda. To również kultura, ludzie, muzyka, fotografia i wydarzenia, dzięki którym można odkrywać nasz region na wiele różnych sposobów.</p><p>Jako Stowarzyszenie Nowoczesne Bieszczady od kilku lat organizujemy wydarzenia, konkursy i spotkania, których wspólnym celem jest promocja Bieszczad i zachęcanie do ich poznawania. Chcemy, aby osoby, które przyjeżdżają tutaj po raz pierwszy – na koncert, konkurs, wystawę czy wydarzenie sportowe – zakochały się w Bieszczadach i miały powód, żeby do nas wracać.</p><p>Jednym z naszych najważniejszych przedsięwzięć jest konkurs fotograficzny „Kocham Bieszczady”, którego w 2026 roku organizujemy już czwartą edycję. Co roku otrzymujemy fotografie pokazujące niezwykłe krajobrazy, przyrodę i charakter naszego regionu. Prezentujemy je w mediach społecznościowych, organizujemy wystawy pokonkursowe, a najlepsze prace trafiają również do wydawanych przez nas kalendarzy.</p><p>Ważnym wydarzeniem stał się także festiwal „Granie Bez Granic”. Za nami już dwie edycje imprezy, której termin nie jest przypadkowy. Organizujemy ją w lipcu, chcąc dodatkowo pobudzić ruch turystyczny w okresie, kiedy sezon w rejonie Ustrzyk Dolnych dopiero nabiera rozpędu. Festiwal ma przyciągać gości spoza regionu, ale jednocześnie być atrakcyjnym wydarzeniem dla mieszkańców Bieszczadów.</p><p>W 2025 roku po raz pierwszy sięgnęliśmy również po inną formę artystycznego pokazania naszego regionu, organizując konkurs malarski „Piękno Bieszczadów – sakralnie i pejzażowo”. Było to dla nas nowe wyzwanie, które pokazało, jak wiele możliwości daje łączenie promocji Bieszczad ze sztuką i twórczością.</p><p>Każde z tych przedsięwzięć jest inne, ale wszystkie łączy jeden cel – chcemy pokazywać Bieszczady, tworzyć powody do przyjazdu i sprawiać, żeby ludzie chcieli tutaj wracać.</p><p>Bo w Bieszczadach można zakochać się na szlaku, ale można też poprzez fotografię, obraz, muzykę i wspólnie przeżywane wydarzenia.</p>",
    "statEditionsOne": "{liczba} edycja festiwalu",
    "statEditionsFew": "{liczba} edycje festiwalu",
    "statEditionsMany": "{liczba} edycji festiwalu",
    "statContestsOne": "{liczba} cykliczny konkurs",
    "statContestsFew": "{liczba} cykliczne konkursy",
    "statContestsMany": "{liczba} cyklicznych konkursów",
    "statExtra": "Wydarzenia co roku",
    "pageTitle": "Kultura i wydarzenia",
    "barEditionsOne": "Edycja festiwalu",
    "barEditionsFew": "Edycje festiwalu",
    "barEditionsMany": "Edycji festiwalu",
    "barContestsOne": "Konkurs cykliczny",
    "barContestsFew": "Konkursy cykliczne",
    "barContestsMany": "Konkursów cyklicznych",
    "stats": "Wykonawców w 2025: 20+\nScen na festiwalu: 3",
    "festivalKicker": "Festiwal Granie Bez Granic",
    "festivalTitle": "Archiwum edycji",
    "festivalLead": "Muzyczne wydarzenie łączące kultury i pokolenia — zobacz relacje z poprzednich edycji festiwalu.",
    "editionNewest": "Najnowsza",
    "editionLink": "Zobacz opis i galerię →",
    "announcementBadge": "Zapowiedź",
    "announcementText": "Z dumą zapraszamy na Festiwal „Granie Bez Granic” — nowe wydarzenie, którego jesteśmy organizatorem. Połączenie koncertów, astronomii i ekologii, w sercu Ustrzyk Dolnych, tam gdzie niebo naprawdę jest ciemne.",
    "upcomingKicker": "Nadchodząca edycja",
    "upcomingTitle": "III edycja festiwalu „Granie Bez Granic”",
    "upcomingText": "Termin i program kolejnej edycji ogłosimy wkrótce w zakładce Aktualności.",
    "upcomingButton": "Śledź aktualności",
    "contestsKicker": "Konkursy",
    "contestsTitle": "Konkursy fotograficzne i malarskie",
    "documentsTitle": "Dokumenty do pobrania",
    "documentPreview": "Podgląd",
    "documentDownload": "Pobierz",
    "contestsLink": "Śledź aktualności →",
    "editionKicker": "Festiwal Granie Bez Granic",
    "editionBack": "← Wróć do Kultury",
    "editionNotFound": "Nie znaleziono edycji",
    "themeBackground": "",
    "themeHero": "",
    "themeTitle": "",
    "themeLead": "",
    "themeBody": "",
    "themeAccent": ""
  },
  "strona-inicjatywy": {
    "heroKicker": "Edukacja i społeczność",
    "heroTitle": "Inicjatywy społeczne i edukacja",
    "heroDescription": "<p>Warsztaty, debaty i projekty budujące kompetencje i głos lokalnej społeczności.</p>",
    "stats": "Warsztaty podcastowe\nCykliczne debaty\nOtwarte dla mieszkańców",
    "pageTitle": "Inicjatywy społeczne i edukacja",
    "eterKicker": "Projekt warsztatowy",
    "eterTitle": "Bieszczady w eterze",
    "eterText": "<p>Cykl warsztatów podcastowych dla lokalnych liderów i liderek. Uczymy planowania odcinków, nagrywania i montażu dźwięku oraz budowania narracji o swojej okolicy — tak, żeby dotrzeć do słuchaczy spoza regionu.</p><p>Efektem warsztatów są realne odcinki podcastu nagrane i wyemitowane przez uczestników projektu.</p>",
    "burzaKicker": "Debaty społeczne",
    "burzaTitle": "Bieszczadzka Burza Mózgów 2026– wspólnie o przyszłości turystyki w Bieszczadach",
    "burzaText": "<p>Jednym z ważnych celów Stowarzyszenia Nowoczesne Bieszczady jest rozwój turystyki. W naszych działaniach koncentrujemy się przede wszystkim na Ustrzykach Dolnych i powiecie bieszczadzkim, ale od początku zależy nam również na współpracy ponad lokalnymi granicami i budowaniu wspólnej, silnej marki całych Bieszczad.</p><p>Właśnie taką ideę ma Bieszczadzka Burza Mózgów – cykl spotkań łączących branżę turystyczną, przedsiębiorców, samorządowców oraz instytucje odpowiedzialne za rozwój i promocję regionu.</p><p>20 kwietnia 2026 roku mieliśmy przyjemność być współorganizatorami i gospodarzami kolejnej edycji wydarzenia, która odbyła się w Niedźwiadku pod Holicą. W spotkaniu uczestniczyło blisko 90 osób związanych z turystyką i rozwojem Bieszczad.</p><p>To właśnie takich rozmów potrzebujemy. Przy jednym stole spotykają się osoby, które na co dzień prowadzą obiekty turystyczne, gastronomiczne i inne firmy, przedstawiciele samorządów oraz instytucji regionalnych. Możemy wspólnie mówić zarówno o problemach – w tym o obserwowanym spadku ruchu turystycznego – jak również o nowych pomysłach, inwestycjach i atrakcjach, które mogą zwiększyć zainteresowanie naszym regionem.</p><p>W tegorocznym spotkaniu uczestniczył m.in. Piotr Pilch – Wicemarszałek Województwa Podkarpackiego, Pani Wioletta Rejman - Dyrektor Departamentu Promocji i Turystyki  Urzędu Marszałkowskiego, Podkarpackiej Regionalnej Organizacji Turystycznej, samorządów z terenu Bieszczad, powiatów bieszczadzkiego i leskiego, Lasów Państwowych oraz liczna reprezentacja branży turystycznej.</p><p>Jednym z najważniejszych tematów tegorocznej edycji była turystyka rowerowa w Bieszczadach. Nasz region ma ogromny potencjał – piękne krajobrazy, zróżnicowany teren i miejsca, które wręcz zachęcają do poznawania ich z perspektywy roweru. Jednocześnie wciąż brakuje nam spójnej i dobrze oznakowanej sieci tras rowerowych.</p><p>Podczas spotkania dużo miejsca poświęcono właśnie temu problemowi oraz planom rozwoju nowych tras i stworzenia bardziej kompleksowej oferty dla rowerzystów.</p><p>Ważne są jednak nie tylko same trasy, ale również usługi, które powstają wokół nich. Zbigniew Prasoł zaprezentował podczas spotkania nowoczesny pomysł na wypożyczalnię rowerów elektrycznych w Ustrzykach Dolnych – system, w którym turysta będzie mógł zamówić odpowiednio dobrany rower wraz z dostawą bezpośrednio do miejsca swojego pobytu.</p><p>Takie przedsięwzięcia pokazują, że rozwój turystyki to nie tylko duże inwestycje infrastrukturalne. To również pomysłowość lokalnych przedsiębiorców, nowe produkty turystyczne i współpraca wielu środowisk.</p><p>Bieszczadzka Burza Mózgów ma być właśnie miejscem takiej współpracy. Chcemy inicjować rozmowę, łączyć ludzi i zachęcać branżę turystyczną oraz samorządy do wspólnego działania.</p><p>Bo Bieszczady możemy skutecznie promować i rozwijać tylko razem.</p>",
    "noteKicker": "Bądź na bieżąco",
    "noteTitle": "Relacje ze spotkań i warsztatów",
    "noteText": "Zdjęcia, podsumowania i najświeższe wieści z „Bieszczad w eterze”, „Bieszczadzkiej Burzy Mózgów” i innych naszych inicjatyw publikujemy na bieżąco w Aktualnościach.",
    "noteButton": "Zobacz aktualności",
    "themeBackground": "",
    "themeHero": "",
    "themeTitle": "",
    "themeLead": "",
    "themeBody": "",
    "themeAccent": ""
  },
  "strona-kontakt": {
    "heroKicker": "Kontakt",
    "heroTitle": "Skontaktuj się z nami",
    "heroDescription": "<p>Masz pytanie, pomysł na współpracę albo chcesz dołączyć do stowarzyszenia? Napisz do nas.</p>",
    "stats": "Odpowiadamy do 48h\nUstrzyki Dolne\nOtwarci na współpracę",
    "pageTitle": "Kontakt",
    "formTitle": "Formularz kontaktowy",
    "formSuccess": "Dziękujemy! Twoja wiadomość została zapisana — odpowiemy najszybciej, jak to możliwe.",
    "formName": "Imię i nazwisko",
    "formNamePlaceholder": "Jan Kowalski",
    "formEmail": "Adres e-mail",
    "formEmailPlaceholder": "jan@przyklad.pl",
    "formMessage": "Wiadomość",
    "formMessagePlaceholder": "W czym możemy pomóc?",
    "formSubmit": "Wyślij wiadomość",
    "infoTitle": "Stowarzyszenie Nowoczesne Bieszczady",
    "socialTitle": "Social media",
    "themeBackground": "",
    "themeHero": "",
    "themeTitle": "",
    "themeLead": "",
    "themeBody": "",
    "themeAccent": ""
  },
  "strona-o-nas": {
    "heroKicker": "Stowarzyszenie",
    "heroTitle": "O nas",
    "heroDescription": "<p>Kim jesteśmy, czym się kierujemy i jak działamy na rzecz Bieszczadów.</p>",
    "stats": "Od 2016 roku\n4 obszary działania\nUstrzyki Dolne",
    "misjaTitle": "Kim jesteśmy / Nasza Misja",
    "misjaText": "<p>Stowarzyszenie Nowoczesne Bieszczady powstało w 2016 roku w Ustrzykach Dolnych. Prowadzimy działalność doradczą, edukacyjną i kulturalną — wspieramy ekonomię społeczną, edukację demokracji lokalnej, aktywność kulturalną oraz rozwój Ustrzyk Dolnych i Powiatu Bieszczadzkiego.</p><p>Naszą misją jest łączenie tradycji z nowoczesnością — pokazywanie, że zrównoważony rozwój Bieszczadów może iść w parze z nowymi technologiami, aktywizacją społeczną i otwartością na zmiany. Wierzymy, że najlepsze pomysły rodzą się we współpracy z mieszkańcami, dlatego większość naszych projektów opiera się na dialogu i realnym udziale lokalnej społeczności.</p><p>Nasi członkowie to przedsiębiorcy, nauczyciele, pracownicy samorządowi i specjaliści różnych branż. Stawiamy na profesjonalizm i zaangażowanie — „Skuteczni dla Was”.</p>",
    "misjaPageTitle": "Kim jesteśmy",
    "celeTitle": "Cele Stowarzyszenia",
    "celeText": "<p>Nasza działalność koncentruje się wokół czterech głównych obszarów:</p>",
    "statutTitle": "Statut Stowarzyszenia",
    "statutText": "<p>Statut Stowarzyszenia Nowoczesne Bieszczady określa cele, zasady działania oraz strukturę organizacyjną naszej organizacji. Pełną treść dokumentu można przeczytać poniżej lub pobrać jako plik PDF.</p>",
    "statutDownload": "Pobierz Statut (PDF)",
    "statutOpen": "Otwórz w nowej karcie",
    "statutHint": "Kliknij stronę, żeby ją powiększyć.",
    "deklaracjaTitle": "Deklaracja członkowska",
    "deklaracjaText": "<p>Chcesz dołączyć do Stowarzyszenia Nowoczesne Bieszczady? Pobierz i wypełnij deklarację członkowską, a następnie dostarcz ją osobiście lub prześlij skan na adres e-mail biura stowarzyszenia.</p>",
    "deklaracjaDownload": "Pobierz deklarację (PDF)",
    "deklaracjaSoon": "Formularz wkrótce dostępny",
    "deklaracjaStep1": "Pobierz i wypełnij formularz deklaracji.",
    "deklaracjaStep2": "Podpisz dokument odręcznie lub elektronicznie.",
    "deklaracjaStep3": "Prześlij skan na {email} lub dostarcz osobiście.",
    "zarzadTitle": "Zarząd i Zespół",
    "zarzadText": "<p>Poznaj osoby, które na co dzień koordynują działania Stowarzyszenia Nowoczesne Bieszczady.</p>",
    "sprawozdaniaTitle": "Sprawozdania i transparentność",
    "sprawozdaniaText": "<p>Transparentność jest dla nas kluczowa. Poniżej publikujemy coroczne sprawozdania merytoryczne i finansowe Stowarzyszenia Nowoczesne Bieszczady.</p>",
    "sprawozdaniaDownload": "Pobierz PDF",
    "sprawozdaniaSoon": "PDF wkrótce",
    "partnerzyTitle": "Partnerzy i Grantodawcy",
    "partnerzyText": "<p>Nasze projekty realizujemy dzięki współpracy i wsparciu finansowemu poniższych instytucji i organizacji.</p>",
    "wolontariatTitle": "Wolontariat",
    "wolontariatText": "",
    "wolontariatEmpty": "Wkrótce zamieścimy tutaj informacje o wolontariacie w Stowarzyszeniu Nowoczesne Bieszczady.",
    "wolontariatOpen": "Pobierz / zobacz",
    "themeBackground": "",
    "themeHero": "",
    "themeTitle": "",
    "themeLead": "",
    "themeBody": "",
    "themeAccent": ""
  },
  "dream-map-settings": {
    "skyTitle": "Cyfrowa Mapa",
    "skyTitleAccent": "Marzeń",
    "skySubtitle": "Ustrzyki Dolne 2036 — Warsztat Przyszłości",
    "skyInfoButton": "O projekcie",
    "skyInfoTitle": "O projekcie",
    "skyInfoText": "<p>Bieszczady to jedno z najciemniejszych miejsc na mapie Polski. Mieszkańcy Ustrzyk Dolnych spojrzeli w to niebo i rozłożyli na nim swoje marzenia o mieście za dekadę.</p><p>Każda gwiazda to postulat zgłoszony podczas warsztatów „Ustrzyki 2036: Warsztat Przyszłości”. Gwiazdozbiory łączą postulaty w kategorie tematyczne — kliknij gwiazdę, by poznać szczegóły.</p>",
    "skyInfoAuthor": "Stowarzyszenie Nowoczesne Bieszczady",
    "skyInfoFooter": "Projekt „Ustrzyki 2036: Warsztat Przyszłości” • 3 warsztaty kreatywne • {liczba} postulatów mieszkańców",
    "filterAll": "Wszystkie",
    "filterCount": "{liczba} postulatów",
    "challengeLabel": "Wyzwanie",
    "solutionLabel": "Propozycja rozwiązania",
    "pageTitle": "Ustrzyki 2036: Warsztat Przyszłości",
    "aboutKicker": "Ustrzyki 2036: Warsztat Przyszłości",
    "aboutTitle": "Skąd wzięła się ta mapa",
    "aboutText": "<p>Inicjatywa „Ustrzyki 2036: Warsztat Przyszłości” to autorski projekt realizowany przez Stowarzyszenie Nowoczesne Bieszczady we współpracy z lokalnymi partnerami: Centrum Koordynacji i Wspierania Aktywności Społeczno-Gospodarczej w Stefkowej oraz Powiatowym Urzędem Pracy w Ustrzykach Dolnych.</p><p>Główną intencją projektu było odejście od tradycyjnych, często biernych formuł konsultacji społecznych na rzecz stworzenia przestrzeni realnego, żywego i twórczego współdecydowania. Chcieliśmy dać mieszkańcom narzędzie do kształtowania przestrzeni publicznej oraz budowania poczucia sprawstwa — udowadniając, że głos każdego z nas ma znaczenie.</p><p>Prezentowana Cyfrowa Mapa Marzeń jest bezpośrednim owocem procesu konsultacji społecznych i pracy warsztatowej. Przy jednym stole usiedli przedstawiciele bardzo różnych środowisk — od seniorów dzielących się mądrością życiową, przez lokalnych liderów i członków organizacji pozarządowych, aż po młodzież z Młodzieżowej Rady Gminy.</p><p>Niniejsza mapa nie jest katalogiem roszczeń ani formą krytyki dotychczasowych działań. Jest głosem troski, dojrzałej odpowiedzialności oraz autentycznej miłości do naszej małej ojczyzny. Traktujemy wypracowane postulaty jako partnerskie zaproszenie do dialogu.</p>",
    "fundingNote": "Inicjatywa jest współfinansowana ze środków otrzymanych od Narodowego Instytutu Wolności — Centrum Rozwoju Społeczeństwa Obywatelskiego w ramach Rządowego Programu Fundusz Inicjatyw Obywatelskich NOWEFIO na lata 2021–2030, za pośrednictwem Stowarzyszenia „Pro Carpathia”.",
    "boardCount": "{liczba} postulatów mieszkańców",
    "boardTitle": "Wszystkie punkty mapy marzeń",
    "boardLead": "Pełna lista wniosków i rekomendacji z warsztatów „Ustrzyki 2036” — wyzwanie i proponowane rozwiązanie przy każdym punkcie.",
    "ideaKicker": "Twój głos",
    "ideaTitle": "Zgłoś swój pomysł",
    "ideaText": "Masz pomysł, jak zmienić Ustrzyki Dolne na lepsze? Opisz go — przeczytamy każde zgłoszenie.",
    "ideaTileLink": "Zgłoś pomysł →",
    "ideaField1": "1. Tytuł pomysłu",
    "ideaField2": "2. Opis problemu do rozwiązania",
    "ideaField3": "3. Propozycja rozwiązania / Twój pomysł",
    "ideaField4": "4. Kontakt (e-mail lub telefon)",
    "ideaSubmit": "Wyślij pomysł",
    "ideaSending": "Wysyłanie…",
    "ideaError": "Nie udało się wysłać zgłoszenia. Spróbuj ponownie za chwilę.",
    "ideaSuccessTitle": "Dziękujemy!",
    "ideaSuccessText": "Twój pomysł do nas dotarł. Skontaktujemy się, jeśli będziemy mieli pytania.",
    "ideaAgain": "Zgłoś kolejny pomysł",
    "themeBackground": "",
    "themeHero": "",
    "themeTitle": "",
    "themeLead": "",
    "themeBody": "",
    "themeAccent": ""
  }
} as const

/** Adres podstrony dla każdego formularza (przycisk „Zobacz na stronie”). */
export const pageTextUrls = {
  "home": "/",
  "site-settings": null,
  "strona-aktualnosci": "/aktualnosci",
  "strona-szlaki": "/szlaki",
  "strona-trasa": "/szlaki",
  "strona-korona": "/korona-gor",
  "strona-kultura": "/kultura",
  "strona-inicjatywy": "/inicjatywy",
  "strona-kontakt": "/kontakt",
  "strona-o-nas": "/o-nas/misja",
  "dream-map-settings": "/ustrzyki-2036"
} as const

export type PageTextName = keyof typeof pageTextDefaults
